### ISSUE TITLE
Improvement: Remove use of Reflection to get reports

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe-labs/silverstripe-reports#43]
Versions: all

---

In [`Report::get_reports`](https://github.com/silverstripe-labs/silverstripe-reports/blob/master/code/Report.php#L218-L222) reflection is used to determine if a class is abstract.

This is bad practice (IMO) and should be re-written. Perhaps any abstract classes should implement an abstract interface, or better yet any *valid* report classes should implement a report interface (`SS_ReportInterface` for example). This would mean you can look them up directly instead of filtering out abstract classes.

**Comment by dhensby** [comment]
This isn't really a bug, so I'm going to close this, I'm afraid.

I don't fully agree with you, either, but happy to hear more about why you think the current approach is bad.

Creating abstract classes is a legitimate approach to OOP. SilverStripe tries to be quite "magical" in how it discovers classes (rather than requiring the dev to register all the classes they want to use) and this means we can pick up abstract classes when looking for those with a common inheritance or even interface implementation.

There's no guarantee that a class won't be abstract just because it does/doesn't implement an interface and having abstract Reports that are then extended by others should be a supported architectural practice.

Having an interface implemented by abstract classes wouldn't work because any class that extends that class will itself implement the abstract interface too. Having an interface for valid Reports is kind of done (except you extend an abstract class instead of implementing an interface) and there's nothing to stop someone creating an abstract class that implements an interface and to stop them seems unduly restrictive.

**Comment by dhensby** [comment]
Hi, thanks for taking the time to post to our issue tracker.

The issue tracker is intended to be used for reporting bugs and not for feature requests or discussions.

If you'd like to request a feature please see our [user voice page](https://silverstripe.uservoice.com) where you can submit your ideas.

If you feel you're capable of solving this problem and submitting a pull request with this feature added, please do so and a member of the team will review it.

If you'd like to discuss a feature idea before submitting a PR, please submit it to our [mailing list](https://groups.google.com/forum/#!forum/silverstripe-dev)

Thanks for taking the time to make this suggestion.

**Comment by robbieaverill** [comment]
Hey @dhensby 

You're right, it's not a bug - more a "best practice" suggestion. I don't think it's a good idea to use reflection in production code.

You're entirely right in terms of SS being able to pick up any class whether abstract or not, and whether it implements an interface should not be the deciding factor. It was merely a suggestion for a way to avoid using reflection by modifying the code to only accept instances of an interface. At the end of the day, an abstract class is no use to a function that "gets a list of SilverStripe reports", so could be a valid way to enforce structure among actual report classes and abstract report classes containing base functionality.

Anyway - I appreciate your taking time to answer :)

Cheers!
Robbie

**Comment by dhensby** [comment]
No worries - we're using Reflections a fair amount in our production code, so this would just be chipping away at an ice burg (not that it's not a reason to improve code) - but I'd definitely be interested in learning more about pros/cons or reflections and how we can solve our problems without it (we had a lot of static parsing and caching which has been moved to reflections for quite good performance gains).
